export type ActionabilityStatus = "high" | "medium" | "low";
export type ConfidenceLevel = "high" | "medium" | "low";

export type ActionabilityInput = Readonly<{
  asOf: Date;
  issue: Readonly<{
    title: string;
    body: string | null;
    labels: readonly string[];
    canonicalUrl: string;
  }>;
}>;
export type ActionabilityFact = Readonly<{
  key: string;
  value: string | number | boolean | null;
  sourceUrl: string;
  observedAt: Date;
  freshnessDays: number;
}>;
export type ActionabilityInference = Readonly<{
  key: string;
  value: string | number | boolean;
  basisFactKeys: readonly string[];
  caution: string;
}>;
export type ActionabilityResult = Readonly<{
  version: "actionability-v2";
  status: ActionabilityStatus;
  score: number;
  confidence: Readonly<{ level: ConfidenceLevel; value: number }>;
  facts: readonly ActionabilityFact[];
  inferences: readonly ActionabilityInference[];
  warnings: readonly string[];
}>;

const POSITIVE_LABEL = /^(?:bug|enhancement|feature|good first issue|help wanted|easy to fix)$/i;
const DISCUSSION_LABEL = /^(?:meta|discuss|discussion|question|rfc|proposal|brainstorm)$/i;
const AUTOMATED_LABEL = /^(?:automated|bot|renovate|dependencies|dependency dashboard)$/i;
const CONCRETE_REQUEST =
  /\b(?:fix|implement|add|remove|replace|support|refactor|prevent|ensure|must|should|expected behavior)\b/i;
const ACCEPTANCE_CRITERIA =
  /(?:^|\n)\s*[-*]\s*\[[ xX]\]|\b(?:acceptance criteria|expected (?:result|outcome|behavior)|definition of done)\b/i;
const REPRODUCTION =
  /\b(?:steps to reproduce|reproducer|minimal example|actual behavior|expected behavior|stack trace)\b/i;
const SPECIFIC_TARGET =
  /`[^`\n]{2,80}`|\b(?:function|method|class|module|file|handler|api|test)\s+[A-Za-z0-9_.\/-]+/i;
const UNRESOLVED_DIRECTION =
  /\b(?:which (?:option|approach)|what do you think|thoughts\?|open to (?:ideas|suggestions)|happy to hear other approaches|alternatively|possible approaches?|approaches worth considering|one option|another option|we could either)\b/i;
const ACCEPTED_DIRECTION =
  /\b(?:we (?:have )?(?:decided|agreed)|accepted approach|consensus is|approved approach|please implement|ready for implementation|implementation direction is)\b/i;
const TRACKING_ISSUE =
  /\b(?:tracking issue|umbrella issue|meta issue|collect(?:ing)? sub-issues|many issues bundled together|public roadmap|dependency dashboard)\b/i;
const AUTOMATED_ISSUE =
  /\b(?:dependency dashboard|renovate updates|detected dependencies|manual job.*renovate|generated by renovate)\b/i;
const PROPOSAL_STYLE =
  /\b(?:proposal|propose|introduce|motivation|why this is feasible|would like to|could improve|should we|consider adding|consider introducing)\b/i;
const NUMBERED_ALTERNATIVE = /^\s*\d+[.)]\s+/gm;
const HEADING_ALTERNATIVE = /^\s*#{1,6}\s+(?:option\s+)?\d+[.:)]?\s+/gim;
const ALTERNATIVE_CONTEXT =
  /\b(?:possible approaches?|approaches worth considering|options? include)\b/i;
const MODERATE_SCOPE =
  /\b(?:multiple files?|multi-file|several (?:files?|components?|modules?)|across (?:the )?(?:codebase|stack)|frontend and backend|client and server|end[- ]to[- ]end)\b/i;
const MIGRATION_SCOPE =
  /\b(?:database migration|schema migration|data migration|backfill|migrate existing|existing rows?|existing records?)\b/i;
const DEPENDENCY_SCOPE =
  /\b(?:blocked by|depends on|dependency on|prerequisite|after #\d+|requires #\d+)\b/i;
const SECURITY_SCOPE =
  /\b(?:security-sensitive|authentication|authorization|credential|token leak|privilege|permission)\b/i;
const RESEARCH_SCOPE =
  /\b(?:external research|research required|unresolved design|architecture change|architectural|breaking change|cross-cutting)\b/i;
const LARGE_IMPLEMENTATION =
  /\b(?:large implementation|multi-step implementation|phased rollout|multiple services|several packages|many components)\b/i;

function confidence(signalCount: number, bodyAvailable: boolean) {
  const value = !bodyAvailable ? 25 : signalCount >= 3 ? 85 : signalCount >= 1 ? 65 : 35;
  return {
    level: value >= 75 ? ("high" as const) : value >= 45 ? ("medium" as const) : ("low" as const),
    value,
  };
}

export function analyzeIssueActionability(input: ActionabilityInput): ActionabilityResult {
  if (Number.isNaN(input.asOf.getTime())) throw new TypeError("Invalid asOf date.");
  if (input.issue.title.trim().length === 0) throw new TypeError("Issue title must not be empty.");
  const labels = input.issue.labels.map((label) => label.trim()).filter(Boolean);
  const body = input.issue.body ?? "";
  const text = `${input.issue.title}\n${body}`;
  const positiveLabels = labels.filter((label) => POSITIVE_LABEL.test(label));
  const discussionLabels = labels.filter((label) => DISCUSSION_LABEL.test(label));
  const automatedLabels = labels.filter((label) => AUTOMATED_LABEL.test(label));
  const concreteRequest = CONCRETE_REQUEST.test(text);
  const acceptanceCriteria = ACCEPTANCE_CRITERIA.test(body);
  const reproduction = REPRODUCTION.test(body);
  const specificTarget = SPECIFIC_TARGET.test(text);
  const acceptedDirection = ACCEPTED_DIRECTION.test(text);
  const unresolvedDirection = !acceptedDirection && UNRESOLVED_DIRECTION.test(text);
  const trackingIssue = TRACKING_ISSUE.test(text);
  const automatedIssue = automatedLabels.length > 0 || AUTOMATED_ISSUE.test(text);
  const independentlyActionable =
    concreteRequest && specificTarget && (acceptanceCriteria || reproduction || acceptedDirection);
  const automatedOrTracking = automatedIssue || (trackingIssue && !independentlyActionable);
  const proposalStyle = !acceptedDirection && PROPOSAL_STYLE.test(text);
  const moderateScope = MODERATE_SCOPE.test(text);
  const migrationScope = MIGRATION_SCOPE.test(text);
  const dependencyScope = DEPENDENCY_SCOPE.test(text);
  const securityScope = SECURITY_SCOPE.test(text);
  const researchScope = RESEARCH_SCOPE.test(text);
  const largeImplementation = LARGE_IMPLEMENTATION.test(text);
  // Scope risk is additive: a migration that also depends on prerequisite work is
  // materially riskier than a clearly specified single-file security fix.
  const complexityPenalty = Math.min(
    35,
    (moderateScope ? 6 : 0) +
      (migrationScope ? 16 : 0) +
      (dependencyScope ? 10 : 0) +
      (securityScope ? 6 : 0) +
      (researchScope ? 12 : 0) +
      (largeImplementation ? 10 : 0),
  );
  const headingAlternativeCount = [...body.matchAll(HEADING_ALTERNATIVE)].length;
  const numberedAlternativeCount = ALTERNATIVE_CONTEXT.test(body)
    ? [...body.matchAll(NUMBERED_ALTERNATIVE)].length
    : 0;
  const alternativeCount = acceptedDirection
    ? 0
    : Math.max(headingAlternativeCount, numberedAlternativeCount);
  const multipleAlternatives = alternativeCount >= 2;

  let score = 50;
  score += Math.min(15, positiveLabels.length * 15);
  score -= Math.min(30, discussionLabels.length * 15);
  if (concreteRequest) score += 10;
  if (acceptanceCriteria) score += 15;
  if (reproduction) score += 10;
  if (specificTarget) score += 10;
  if (acceptedDirection) score += 30;
  if (unresolvedDirection) score -= 15;
  if (multipleAlternatives) score -= 20;
  if (trackingIssue) score -= 35;
  if (automatedIssue) score -= 60;
  if (proposalStyle && !acceptanceCriteria && !reproduction) score -= 10;
  score = Math.min(100, Math.max(0, score));
  score -= complexityPenalty;
  score = Math.min(100, Math.max(0, score));
  if (automatedOrTracking) score = Math.min(score, 20);

  const scopeRisk =
    complexityPenalty === 0
      ? "self-contained"
      : migrationScope && dependencyScope
        ? "migration with prerequisite dependencies"
        : migrationScope
          ? "migration or data-backfill risk"
          : dependencyScope
            ? "dependency-sensitive"
            : researchScope || largeImplementation
              ? "complex or cross-cutting"
              : securityScope
                ? "security-sensitive"
                : "moderate multi-component scope";
  const fact = (key: string, value: string | number | boolean | null): ActionabilityFact => ({
    key,
    value,
    sourceUrl: input.issue.canonicalUrl,
    observedAt: input.asOf,
    freshnessDays: 0,
  });
  const facts: ActionabilityFact[] = [
    fact("actionability.labels", labels.length === 0 ? "None" : labels.join(", ")),
    fact("actionability.discussionLabelCount", discussionLabels.length),
    fact("actionability.alternativeCount", alternativeCount),
    fact("actionability.acceptedDirection", acceptedDirection),
    fact("actionability.acceptanceCriteria", acceptanceCriteria),
    fact("actionability.concreteRequest", concreteRequest),
    fact("actionability.trackingIssue", trackingIssue),
    fact("actionability.automatedIssue", automatedIssue),
    fact("actionability.automatedOrTracking", automatedOrTracking),
    fact("actionability.complexityPenalty", complexityPenalty),
    fact("actionability.scopeRisk", scopeRisk),
    fact("actionability.proposalStyle", proposalStyle),
  ];
  const status: ActionabilityStatus = score >= 70 ? "high" : score >= 40 ? "medium" : "low";
  const signalCount = [
    positiveLabels.length > 0,
    discussionLabels.length > 0,
    automatedLabels.length > 0,
    concreteRequest,
    acceptanceCriteria,
    reproduction,
    specificTarget,
    acceptedDirection,
    unresolvedDirection,
    multipleAlternatives,
    trackingIssue,
    automatedIssue,
    proposalStyle,
    moderateScope,
    migrationScope,
    dependencyScope,
    securityScope,
    researchScope,
    largeImplementation,
  ].filter(Boolean).length;
  const warnings: string[] = [];
  if (input.issue.body === null || body.trim().length === 0)
    warnings.push("Issue description is unavailable, so actionability is uncertain.");
  if (signalCount === 0)
    warnings.push("No strong contribution-readiness or discussion signals were detected.");
  if (proposalStyle && !acceptanceCriteria && !reproduction)
    warnings.push(
      "The issue reads like a proposal or coordination item without concrete acceptance or reproduction evidence.",
    );
  if (complexityPenalty > 0)
    warnings.push(
      `Implementation scope reduces actionability by ${complexityPenalty} points because the issue is ${scopeRisk}.`,
    );
  if (automatedIssue)
    warnings.push(
      "This issue appears to be automated infrastructure or dependency-management output rather than a standalone contribution task.",
    );
  else if (trackingIssue)
    warnings.push(
      "This issue appears to be a roadmap, tracker, or umbrella item rather than a single contribution task.",
    );

  return {
    version: "actionability-v2",
    status,
    score,
    confidence: confidence(signalCount, input.issue.body !== null && body.trim().length > 0),
    facts,
    inferences: [
      {
        key: "actionability.classification",
        value: status,
        basisFactKeys: facts.map((item) => item.key),
        caution:
          "Observable issue text and labels indicate readiness, but maintainers can clarify or change direction later.",
      },
    ],
    warnings,
  };
}
